const HIGHLIGHT_MATCH_SENSITIVITY = 0.6;
const SUCCESS_SUBSCRIPTION_TOAST_MESSAGE = "구독이 완료되었습니다.";
const ERROR_SUBSCRIPTION_TOAST_MESSAGE = "구독에 실패했습니다.";
const SUCCESS_UNSUBSCRIPTION_TOAST_MESSAGE = "구독이 취소되었습니다.";
const ERROR_UNSUBSCRIPTION_TOAST_MESSAGE = "구독 취소에 실패했습니다.";

export {
  HIGHLIGHT_MATCH_SENSITIVITY,
  SUCCESS_SUBSCRIPTION_TOAST_MESSAGE,
  ERROR_SUBSCRIPTION_TOAST_MESSAGE,
  SUCCESS_UNSUBSCRIPTION_TOAST_MESSAGE,
  ERROR_UNSUBSCRIPTION_TOAST_MESSAGE,
};
